"""Compliance document generation.

Every :class:`DocumentType` has a template covering the structure the EU AI Act
expects for that artefact. Templates are rendered from live system data - the
risk classification, its reasoning and the current state of the compliance
checklist - so a generated document reflects what the user has actually done.
"""

import html
import logging
import os
import re
import tempfile
from datetime import datetime
from pathlib import Path
from string import Template
from typing import Dict, List, Optional

from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    HRFlowable,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.ai_system import AISystem, RiskLevel
from app.models.compliance import ComplianceItem, ItemStatus
from app.models.document import Document, DocumentType
from app.models.user import User

logger = logging.getLogger(__name__)

RISK_LEVEL_LABELS = {
    RiskLevel.UNACCEPTABLE: "Unacceptable (prohibited under Article 5)",
    RiskLevel.HIGH: "High risk (Article 6 / Annex III)",
    RiskLevel.LIMITED: "Limited risk (Article 50 transparency duties)",
    RiskLevel.MINIMAL: "Minimal risk",
}

STATUS_LABELS = {
    ItemStatus.PENDING: "Not started",
    ItemStatus.IN_PROGRESS: "In progress",
    ItemStatus.COMPLETED: "Complete",
    ItemStatus.NOT_APPLICABLE: "Not applicable",
}

CHECKBOXES = {
    ItemStatus.PENDING: "[ ]",
    ItemStatus.IN_PROGRESS: "[~]",
    ItemStatus.COMPLETED: "[x]",
    ItemStatus.NOT_APPLICABLE: "[-]",
}

FOOTER = "\n---\nGenerated by the EU AI Act Compliance Tool on $date.\n"


TEMPLATES: Dict[DocumentType, str] = {
    DocumentType.TECHNICAL_DOCUMENTATION: """
# Technical Documentation - $system_name

Prepared by $company_name on $date. Structure follows Annex IV of Regulation
(EU) 2024/1689, referenced by Article 11.

## 1. General description
- System name: $system_name
- Version: $version
- Provider: $company_name
- Intended purpose: $use_case
- Sector: $sector
- Risk classification: $risk_level_label

$description

## 2. Elements of the system and development process
- Design specification, architecture and computational resources used
- Third-party tools, pre-trained models and libraries relied upon
- Design choices made to meet the requirements of Chapter III, Section 2

## 3. Data requirements
See the data governance policy for the full account of training, validation and
testing datasets, their provenance, labelling and the bias examination.

## 4. Monitoring, functioning and control
- Expected accuracy and the metrics used to measure it
- Foreseeable unintended outcomes and sources of risk
- Human oversight measures in place (see the human oversight plan)
- Input data specifications and known limitations

## 5. Performance metrics
Record the accuracy, robustness and fairness metrics measured before release,
broken down by the groups the system is used on.

## 6. Risk management system
Summary of the Article 9 process: identified risks, their evaluation and the
mitigation measures adopted.

$classification_reasons

## 7. Lifecycle changes
Log every substantial modification and the date it was made, together with the
re-assessment it triggered.

## 8. Standards applied
List the harmonised standards applied in full or in part, and where they were
not applied, the solutions adopted to meet the requirements.

## 9. Post-market monitoring plan
Describe how performance data is collected from deployers, who reviews it, and
how findings feed back into the risk management system.

## 10. Compliance status at time of generation
Overall completion: $compliance_score%

$checklist
$footer
""",

    DocumentType.RISK_ASSESSMENT: """
# Risk Assessment Report - $system_name

Prepared by $company_name on $date.

## Executive summary
$system_name is an AI system used for $use_case in the $sector sector. It is
classified as **$risk_level_label** with a classification confidence of
$confidence.

$description

## 1. Classification rationale
$classification_reasons

Provisions engaged: $applicable_articles

## 2. Annex III areas engaged
$annex_areas

## 3. Identified risk areas

### 3.1 Data-related risks
- Representativeness of training, validation and testing data
- Bias affecting protected groups and the measures taken to detect it
- Personal data minimisation and lawful basis for processing

### 3.2 Model-related risks
- Accuracy limits and error distribution across subgroups
- Robustness to distribution shift, adversarial input and data poisoning
- Explainability sufficient for a deployer to interpret the output

### 3.3 Deployment risks
- Automation bias in the humans reviewing the output
- Foreseeable misuse outside the intended purpose
- Integration failures with upstream and downstream systems

## 4. Mitigation measures and their status
$checklist

## 5. Compliance requirements
$requirements

## 6. Next steps
$next_steps

## 7. Review schedule
This assessment must be reviewed whenever the intended purpose changes, after
any substantial modification, and at least annually.
$footer
""",

    DocumentType.CONFORMITY_DECLARATION: """
# EU Declaration of Conformity

Issued under Article 47 of Regulation (EU) 2024/1689.

## 1. AI system identification
- System name and type: $system_name
- Version: $version
- Intended purpose: $use_case
- Risk classification: $risk_level_label

## 2. Provider
- Name: $company_name
- Contact: ____________________________________

## 3. Declaration
This declaration of conformity is issued under the sole responsibility of the
provider named above. We declare that the AI system identified in section 1 is
in conformity with Regulation (EU) 2024/1689 and, where applicable, with the
other Union legislation listed in section 6.

## 4. Requirements addressed
$checklist

## 5. Conformity assessment procedure
Internal control, Annex VI. Completed on: ____________________

## 6. Other Union legislation applied
- Regulation (EU) 2016/679 (GDPR), where personal data is processed
- ____________________________________

## 7. Signature
- Place and date of issue: ____________________
- Name and function: ____________________________________
- Signature: ____________________________________

This declaration must be kept at the disposal of the national competent
authorities for 10 years after the system is placed on the market.
$footer
""",

    DocumentType.DATA_GOVERNANCE: """
# Data Governance Policy - $system_name

Prepared by $company_name on $date, addressing Article 10 of Regulation (EU)
2024/1689.

## 1. Scope
Applies to the training, validation and testing datasets used to build
$system_name, whose intended purpose is $use_case.

## 2. Design choices
- Purpose of each dataset and how it relates to the intended purpose
- Assumptions made about what the data represents and measures
- Rationale for the labelling taxonomy in use

## 3. Data collection and provenance
- Origin of each dataset and the lawful basis for its use
- For personal data: collection purpose, controller and retention period
- Third-party datasets, their licence terms and known limitations

## 4. Data preparation
- Annotation, labelling, cleaning, enrichment and aggregation steps
- Handling of missing values and outliers
- Train / validation / test split strategy and leakage controls

## 5. Bias examination
- Groups assessed for possible bias
- Method used (for example subgroup performance comparison)
- Findings and the measures taken in response
- Residual bias accepted, with justification

## 6. Data quality criteria
Datasets must be relevant, sufficiently representative and, to the best extent
possible, free of errors and complete in view of the intended purpose.

- Quality checks run and their frequency
- Owner accountable for each dataset
- Trigger conditions for refreshing a dataset

## 7. Special categories of personal data
Where special category data is processed for bias detection under Article 10(5),
record the safeguards applied: access restriction, pseudonymisation, deletion
after the bias assessment, and the prohibition on transmitting the data onward.

## 8. Governance status
Overall completion: $compliance_score%

$checklist
$footer
""",

    DocumentType.TRANSPARENCY_NOTICE: """
# AI Transparency Notice - $system_name

Published by $company_name. Last updated $date. Issued under Article 50 of
Regulation (EU) 2024/1689.

## You are interacting with an AI system
$system_name is an artificial intelligence system operated by $company_name.
It is used for $use_case.

$description

## What the system does
- It processes the input you provide in order to produce the output you see
- Its output is a suggestion or an assessment, not a statement of fact
- Risk classification under the EU AI Act: $risk_level_label

## What the system does not do
- It does not replace the human decision-maker responsible for the outcome
- It is not designed for use outside the intended purpose stated above

## Limitations
Accuracy varies with the quality and completeness of the input. Known
limitations and the expected level of accuracy are recorded in the technical
documentation and are available on request.

## Human oversight
A trained person reviews the system's output before it is acted upon, and can
disregard, override or reverse it.

## Your rights
- You can ask for an explanation of the output that concerns you
- You can request human review of a decision informed by this system
- Where personal data is processed, your GDPR rights apply in full

## Contact
$company_name - ____________________________________
$footer
""",

    DocumentType.HUMAN_OVERSIGHT_PLAN: """
# Human Oversight Plan - $system_name

Prepared by $company_name on $date, addressing Article 14 of Regulation (EU)
2024/1689.

## 1. Purpose
Define the measures that allow the people overseeing $system_name to prevent or
minimise risks to health, safety and fundamental rights during use for
$use_case.

## 2. Oversight roles
- Reviewer: reviews individual outputs before they are acted upon
- System owner: monitors aggregate performance and drift
- Escalation owner: authorised to suspend the system

Named holders: ____________________________________

## 3. Oversight measures built into the system
- Output is presented with the confidence and the main contributing factors
- The reviewer can see the input the output was derived from
- Every output can be overridden, with the override recorded
- A documented stop button halts the system without a code change

## 4. Competence and training
Reviewers are trained on the system's capacities and limitations, on automation
bias, and on how to interpret the output correctly. Training is refreshed after
every substantial modification.

## 5. Escalation procedure
1. Reviewer flags an anomalous or harmful output
2. System owner triages within one working day
3. Escalation owner decides whether to suspend the system
4. Serious incidents are reported under Article 73 within 15 days

## 6. Evidence of effectiveness
- Override rate and the reasons recorded
- Time spent per review
- Outcome of periodic sampling of accepted outputs

## 7. Current oversight status
$checklist
$footer
""",

    DocumentType.INCIDENT_REPORT: """
# Serious Incident Report - $system_name

Prepared by $company_name on $date, under Article 73 of Regulation (EU)
2024/1689.

## 1. Reporting entity
- Provider: $company_name
- AI system: $system_name (version $version)
- Risk classification: $risk_level_label
- Intended purpose: $use_case

## 2. Incident summary
- Date and time the incident occurred: ____________________
- Date and time the provider became aware: ____________________
- Member State where the incident occurred: ____________________
- Description of what happened: ____________________________________

## 3. Incident category
- [ ] Death or serious harm to a person's health
- [ ] Serious and irreversible disruption of critical infrastructure
- [ ] Infringement of obligations protecting fundamental rights
- [ ] Serious harm to property or the environment

## 4. Affected persons
Number and category of the people affected: ____________________

## 5. Immediate corrective action taken
____________________________________

## 6. Root cause analysis
- Suspected cause and the evidence for it
- Whether the system was used within its intended purpose
- Whether the human oversight measures operated as designed

## 7. Preventive measures
Changes to the system, the data, the documentation or the oversight process
that will prevent recurrence, and the date each will be in place.

## 8. Notification log
- Market surveillance authority notified on: ____________________
- Deployers notified on: ____________________
- Affected persons notified on: ____________________

Reporting deadline: immediately after establishing the causal link, and no later
than 15 days after becoming aware of the incident (2 days for a widespread
infringement or critical infrastructure disruption, 10 days for a death).
$footer
""",
}


def _bullet_list(values: List[str], empty: str) -> str:
    if not values:
        return empty
    return "\n".join(f"- {value}" for value in values)


def _numbered_list(values: List[str], empty: str) -> str:
    if not values:
        return empty
    return "\n".join(f"{index}. {value}" for index, value in enumerate(values, 1))


def _checklist_block(items: List[ComplianceItem]) -> str:
    if not items:
        return "No compliance checklist has been generated for this system yet."

    lines = []
    for item in items:
        lines.append(
            f"- {CHECKBOXES[item.status]} **{item.article}** - {item.title} "
            f"({STATUS_LABELS[item.status]})"
        )
        if item.evidence_notes:
            lines.append(f"  - Evidence: {item.evidence_notes}")
    return "\n".join(lines)


def build_context(
    ai_system: AISystem,
    owner: User,
    include_recommendations: bool = True,
) -> Dict[str, str]:
    """Assemble every placeholder a template can reference."""
    assessment = ai_system.latest_assessment
    responses = ai_system.questionnaire_responses or {}

    reasons: List[str] = []
    requirements: List[str] = []
    next_steps: List[str] = []
    articles: List[str] = []
    annex_areas: List[str] = []
    confidence = "not assessed"

    if assessment:
        for finding in assessment.findings or []:
            reasons.extend(finding.get("reasons", []))
            articles.extend(finding.get("applicable_articles", []))
            annex_areas.extend(finding.get("annex_iii_areas", []))
            if finding.get("confidence") is not None:
                confidence = f"{int(round(float(finding['confidence']) * 100))}%"
        for recommendation in assessment.recommendations or []:
            requirements.extend(recommendation.get("requirements", []))
            next_steps.extend(recommendation.get("next_steps", []))

    if not include_recommendations:
        next_steps = []

    risk_level = ai_system.risk_level
    now = datetime.utcnow()

    return {
        "system_name": ai_system.name,
        "version": ai_system.version or "1.0",
        "use_case": ai_system.use_case or responses.get("use_case_category") or "not specified",
        "sector": ai_system.sector or "not specified",
        "description": ai_system.description or "No description has been provided yet.",
        "risk_level": risk_level.value if risk_level else "not assessed",
        "risk_level_label": (
            RISK_LEVEL_LABELS[risk_level] if risk_level else "Not yet assessed"
        ),
        "company_name": owner.company_name or owner.full_name or owner.email,
        "date": now.strftime("%Y-%m-%d"),
        "confidence": confidence,
        "compliance_score": str(ai_system.compliance_score or 0),
        "classification_reasons": _bullet_list(
            reasons, "No classification has been recorded for this system yet."
        ),
        "requirements": _bullet_list(
            requirements, "Run the risk classification to derive the requirements."
        ),
        "next_steps": _numbered_list(
            next_steps, "Run the risk classification to derive the next steps."
        ),
        "applicable_articles": ", ".join(dict.fromkeys(articles)) or "not yet determined",
        "annex_areas": _bullet_list(
            list(dict.fromkeys(annex_areas)),
            "No Annex III area was engaged by the questionnaire answers.",
        ),
        "checklist": _checklist_block(list(ai_system.compliance_items)),
        "footer": "",  # filled in by render_document
    }


def render_document(
    ai_system: AISystem,
    owner: User,
    document_type: DocumentType,
    include_recommendations: bool = True,
) -> str:
    """Render the markdown body of a compliance document."""
    template = TEMPLATES.get(document_type)
    if template is None:
        raise KeyError(f"No template available for {document_type.value}")

    context = build_context(ai_system, owner, include_recommendations)
    context["footer"] = Template(FOOTER).safe_substitute(date=context["date"])
    return Template(template).safe_substitute(context).strip() + "\n"


def next_version(existing: List[Document]) -> str:
    """Documents of the same type for the same system are versioned 1.0, 1.1..."""
    highest = 0
    for document in existing:
        match = re.match(r"^1\.(\d+)$", document.version or "")
        if match:
            highest = max(highest, int(match.group(1)) + 1)
    return f"1.{highest}"


def generate_document(
    db: Session,
    ai_system: AISystem,
    owner: User,
    document_type: DocumentType,
    include_recommendations: bool = True,
) -> Document:
    """Create and persist a generated compliance document."""
    from app.models.document import DocumentStatus

    content = render_document(ai_system, owner, document_type, include_recommendations)

    siblings = [
        document
        for document in ai_system.documents
        if document.document_type == document_type
    ]

    document = Document(
        owner_id=owner.id,
        ai_system_id=ai_system.id,
        title=f"{document_type.value.replace('_', ' ').title()} - {ai_system.name}",
        document_type=document_type,
        status=DocumentStatus.GENERATED,
        content=content,
        version=next_version(siblings),
    )
    db.add(document)
    db.flush()
    return document


# --- PDF export ------------------------------------------------------------ #

_INLINE_BOLD = re.compile(r"\*\*(.+?)\*\*")


def _inline_markup(text: str) -> str:
    """Escape the text for reportlab, then re-apply the bold spans."""
    escaped = html.escape(text, quote=False)
    return _INLINE_BOLD.sub(r"<b>\1</b>", escaped)


def _styles():
    sheet = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle(
            "DocH1", parent=sheet["Heading1"], fontSize=18, spaceAfter=10
        ),
        "h2": ParagraphStyle(
            "DocH2", parent=sheet["Heading2"], fontSize=14, spaceBefore=12, spaceAfter=6
        ),
        "h3": ParagraphStyle(
            "DocH3", parent=sheet["Heading3"], fontSize=12, spaceBefore=8, spaceAfter=4
        ),
        "body": ParagraphStyle(
            "DocBody",
            parent=sheet["BodyText"],
            fontSize=10,
            leading=14,
            alignment=TA_LEFT,
        ),
        "bullet": ParagraphStyle(
            "DocBullet", parent=sheet["BodyText"], fontSize=10, leading=14
        ),
    }


def _flush_list(buffer: List[tuple], styles, story: List) -> None:
    """Emit the buffered list items as a single reportlab list flowable."""
    if not buffer:
        return
    kind = buffer[0][0]
    story.append(
        ListFlowable(
            [
                ListItem(Paragraph(_inline_markup(text), styles["bullet"]))
                for _, text in buffer
            ],
            bulletType="bullet" if kind == "bullet" else "1",
            leftIndent=16,
            bulletFontSize=7 if kind == "bullet" else 10,
        )
    )
    story.append(Spacer(1, 4))
    buffer.clear()


def markdown_to_story(content: str, styles) -> List:
    """Translate the generated markdown subset into reportlab flowables."""
    story: List = []
    buffer: List[tuple] = []

    def push(kind: str, text: str) -> None:
        if buffer and buffer[0][0] != kind:
            _flush_list(buffer, styles, story)
        buffer.append((kind, text))

    for raw_line in content.splitlines():
        stripped = raw_line.strip()

        if not stripped:
            _flush_list(buffer, styles, story)
            continue

        if stripped == "---":
            _flush_list(buffer, styles, story)
            story.append(Spacer(1, 6))
            story.append(HRFlowable(width="100%", thickness=0.5))
            story.append(Spacer(1, 6))
            continue

        for prefix, style in (("### ", "h3"), ("## ", "h2"), ("# ", "h1")):
            if stripped.startswith(prefix):
                _flush_list(buffer, styles, story)
                story.append(
                    Paragraph(_inline_markup(stripped[len(prefix):]), styles[style])
                )
                break
        else:
            if stripped.startswith("- ") or stripped.startswith("* "):
                push("bullet", stripped[2:])
                continue

            numbered = re.match(r"^\d+\.\s+(.*)$", stripped)
            if numbered:
                push("number", numbered.group(1))
                continue

            _flush_list(buffer, styles, story)
            story.append(Paragraph(_inline_markup(stripped), styles["body"]))

    _flush_list(buffer, styles, story)
    if not story:
        story.append(Paragraph("This document has no content yet.", styles["body"]))
    return story


def _pdf_filename(document: Document) -> str:
    """A filesystem-safe name derived only from server-controlled fields."""
    version = re.sub(r"[^A-Za-z0-9._-]", "_", str(document.version or "1.0"))
    return f"document-{document.id}-v{version}.pdf"


def export_pdf(document: Document, output_dir: Optional[str] = None) -> str:
    """Render a document to PDF and return the file path.

    The PDF is built into a sibling temporary file and moved into place, so a
    reader downloading the previous export never sees a half-written file and a
    failed build never leaves a truncated PDF behind for the next download to
    serve.
    """
    target_dir = Path(output_dir or settings.DOCUMENT_STORAGE_DIR)
    target_dir.mkdir(parents=True, exist_ok=True)
    path = target_dir / _pdf_filename(document)

    handle, temp_name = tempfile.mkstemp(
        dir=str(target_dir), prefix=f".{path.stem}-", suffix=".part"
    )
    os.close(handle)
    temp_path = Path(temp_name)

    try:
        pdf = SimpleDocTemplate(
            str(temp_path),
            pagesize=A4,
            title=document.title,
            author="EU AI Act Compliance Tool",
            leftMargin=20 * mm,
            rightMargin=20 * mm,
            topMargin=18 * mm,
            bottomMargin=18 * mm,
        )
        pdf.build(markdown_to_story(document.content or "", _styles()))
        os.replace(temp_path, path)
    except OSError:
        # On Windows the replace fails while another request has the target
        # open. A concurrent export produced the same bytes, so keep that one.
        _unlink_quietly(temp_path)
        if not path.exists():
            raise
    except Exception:
        _unlink_quietly(temp_path)
        raise

    return str(path)


def _unlink_quietly(path: Path) -> None:
    """Best-effort delete: a leftover temp file must not mask the real error."""
    try:
        path.unlink(missing_ok=True)
    except OSError:  # pragma: no cover - platform dependent
        logger.warning("Could not remove %s", path)


def remove_pdf(file_path: Optional[str]) -> None:
    """Drop a rendered PDF, tolerating one that is already gone or locked.

    A stale or unreadable file on disk must never stop the database row from
    being deleted, so this never raises.
    """
    if not file_path:
        return
    _unlink_quietly(Path(file_path))


__all__ = [
    "TEMPLATES",
    "build_context",
    "export_pdf",
    "remove_pdf",
    "generate_document",
    "markdown_to_story",
    "next_version",
    "render_document",
]
