"""initial schema

Revision ID: 0f1aa33f8cce
Revises: 
Create Date: 2026-07-31 00:23:31.409987
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f1aa33f8cce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'STARTER', 'GROWTH', 'SCALE', name='subscriptiontier'), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('ai_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('use_case', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('risk_level', sa.Enum('UNACCEPTABLE', 'HIGH', 'LIMITED', 'MINIMAL', name='risklevel'), nullable=True),
    sa.Column('compliance_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'UNDER_REVIEW', 'COMPLIANT', 'NON_COMPLIANT', name='compliancestatus'), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('questionnaire_responses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_systems_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_systems_owner_id'), ['owner_id'], unique=False)

    op.create_table('compliance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_system_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('article', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('RISK_MANAGEMENT', 'DATA_GOVERNANCE', 'DOCUMENTATION', 'RECORD_KEEPING', 'TRANSPARENCY', 'HUMAN_OVERSIGHT', 'ROBUSTNESS', 'REGISTRATION', 'GOVERNANCE', name='requirementcategory'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'NOT_APPLICABLE', name='itemstatus'), nullable=False),
    sa.Column('evidence_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_items_ai_system_id'), ['ai_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_items_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_items_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ai_system_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('TECHNICAL_DOCUMENTATION', 'RISK_ASSESSMENT', 'CONFORMITY_DECLARATION', 'DATA_GOVERNANCE', 'TRANSPARENCY_NOTICE', 'HUMAN_OVERSIGHT_PLAN', 'INCIDENT_REPORT', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'REVIEWED', 'APPROVED', 'ARCHIVED', name='documentstatus'), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_ai_system_id'), ['ai_system_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_system_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.Enum('UNACCEPTABLE', 'HIGH', 'LIMITED', 'MINIMAL', name='risklevel'), nullable=True),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('data_governance_score', sa.Integer(), nullable=True),
    sa.Column('transparency_score', sa.Integer(), nullable=True),
    sa.Column('human_oversight_score', sa.Integer(), nullable=True),
    sa.Column('robustness_score', sa.Integer(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_system_id'], ['ai_systems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_assessments_id'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_ai_system_id'))

    op.drop_table('documents')
    with op.batch_alter_table('compliance_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_items_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_items_code'))
        batch_op.drop_index(batch_op.f('ix_compliance_items_ai_system_id'))

    op.drop_table('compliance_items')
    with op.batch_alter_table('ai_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_systems_owner_id'))
        batch_op.drop_index(batch_op.f('ix_ai_systems_id'))

    op.drop_table('ai_systems')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
